prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views as v

urlpatterns = [
    path('', v.home, name='home'),
    path('contact_us/', v.contact_us, name='contact_us'),
    path('accounts/', include('register.urls', namespace='register')),
    path('articles/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

register/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views


from . import views
app_name = 'register'
urlpatterns = [
    path('', views.membership, name='membership'),
    path('login/', views.login_page, name='login_page'),
    path('register/', views.create_account_page, name='create_account_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),








]

register/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Skill(models.Model):
    skill_name = models.CharField(max_length=100, null=True) 
    def __str__(self):
        return self.skill_name
        
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, null=True, blank=True)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    email = models.EmailField(null=True,blank=True)
    phone = models.CharField(max_length=100, null=True,blank=True)
    city = models.CharField(max_length=100,null=True,blank=True)
    bio = models.TextField(null=True,blank=True)
    profession = models.CharField(max_length=100, null=True, blank=True,default='None')
    image = models.ImageField(upload_to='profile_img/', null=True,blank=True, default='avatar.png') 
    skills = models.ManyToManyField(Skill, null=True,blank=True)

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def save_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(
            user=instance,
            first_name=instance.first_name,
            last_name=instance.last_name,
            email=instance.email,
        )
    

register/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.forms import PasswordChangeForm, SetPasswordForm
from django.contrib.auth import  password_validation


class UserForm(UserCreationForm):
    email_error_messages = {
        'email_is_not_unique':('The email is already exist !'),
    }
    password1 = forms.CharField(
        label=("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                        'placeholder':'password',
                                        'required': 'true',

        })
    )
    password2 = forms.CharField(
        label=("Password confirmation"),
        widget=forms.PasswordInput(attrs={'class': 'form-control',
                                        'placeholder':'Enter the same password as above, for verification.',
                                        'type': 'password',
                                        'required': 'true',
        })
    )
    email = forms.CharField(
        label=("Email"),
        widget=forms.TextInput(attrs={'class': 'form-control',
                                    'type': 'email',
                                    'placeholder': 'Email address',
                                    'required': 'true'
        })
    )
    class Meta:
        model=User
        fields=['first_name','last_name','username','email','password1','password2']
        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control','placeholder':'First name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','placeholder':'Last name'}),
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),
        }



    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                self.email_error_messages['email_is_not_unique'],
                code='email_is_not_unique',
            )
        return email

        


class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields='__all__'
        exclude=['user']
        widgets={
            'first_name':forms.TextInput(attrs={'class':'form-control','name':'first_name','id':'first_name', 'placeholder':'first name'}),
            'last_name':forms.TextInput(attrs={'class':'form-control','name':'last_name','id':'last_name', 'placeholder':'last name'}),
            'email':forms.TextInput(attrs={'class':'form-control','name':'email','id':'email', 'placeholder':'you@gmail.com'}),
            'phone':forms.TextInput(attrs={'class':'form-control','name':'phone','id':'phone', 'placeholder':'enter phone'}),
            'city':forms.TextInput(attrs={'class':'form-control','name':'location','id':'location', 'placeholder':'Somewhere'}),
            'bio':forms.Textarea(attrs={'class':'form-control' ,'placeholder':'Bio'}),
            'image':forms.FileInput(attrs={'class':'custom-file-input','id':'inputGroupFile01'}),
            'profession':forms.TextInput(attrs={'class':'form-control','name':'profession','id':'profession', 'placeholder':'what is your profession'}),
            'skills':forms.SelectMultiple(attrs={'class':'form-control','id':'exampleFormControlSelect2'},)
        }
    


class CustomPasswordChange(PasswordChangeForm):
    error_css_class = 'has-error'
    error_messages = {'password_incorrect':
                "The old password is not correct. Please try again."}
    password_error_messages = {
        'password_mismatch': ('The two password fields didn’t match.'),
    }
    old_password = forms.CharField(required=True, label='Old Password',
                    widget=forms.PasswordInput(attrs={
                    'class': 'form-control',
                    'placeholder':'Enter you old password ..'
                    }),
                    error_messages={
                    'required': 'The password can not be empty'})

    new_password1 = forms.CharField(required=True, label='New Password',
                    widget=forms.PasswordInput(attrs={
                    'class': 'form-control',
                    'placeholder':'Enter you New password ..'
                    }),
                    error_messages={
                    'required': 'The password can not be empty'})
    new_password2 = forms.CharField(required=True, label='Confirm New Password',
                    widget=forms.PasswordInput(attrs={
                    'class': 'form-control',
                    'placeholder':'Confirm you New password ..'
                    }),
                    error_messages={
                    'required': 'The password can not be empty'})

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.password_error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password2, self.user)
        return password2

register/views.py
from django.shortcuts import render,redirect
from .forms import *
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from .models import *
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .deco import *

# Create your views here.
@unauthenticated_user
def membership(request):
    return render(request, 'register/membership.html')
@unauthenticated_user
def create_account_page(request):
    form = UserForm()
    if request.method=='POST':
        form = UserForm(request.POST)
        if form.is_valid():
            new_form = form.save()
            username = request.POST.get('username') 
            password = request.POST.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            messages.success(request, 'Thank you for join our website "'+username+'" enjoy 🥳')
            return redirect('/')
    context = {
        'form':form
    }
    return render(request, 'register/create_account_page.html', context)

@unauthenticated_user
def login_page(request):
    if request.method=='POST':
        username = request.POST.get('username') 
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Welcome Back "'+username+'"' )
            return redirect(reverse('main:articles'))
        else:
            messages.error(request, 'Username or password is incorrect !')
    return render(request, 'register/login_page.html')


def logout_page(request):
    logout(request)
    return redirect(reverse('main:articles'))


def profile(request):
    user = request.user.profile
    context = {
        'user':user
    }
    return render(request, 'register/profile.html', context)

def edit_profile(request):
    data = request.user.profile
    form = ProfileForm(instance=data)
    if request.method=='POST':
        form = ProfileForm(request.POST,request.FILES,instance=data)
        if form.is_valid():
            new_form = form.save()
            new_form.user = request.user
            new_form.save()
            return redirect('/accounts/profile/')
            
            
    context = {
        'form':form
    }
    return render(request, 'register/edit_profile.html', context)


def change_password(request):
    form = CustomPasswordChange(user=request.user)
    if request.method=='POST':
        form = CustomPasswordChange(data=request.POST,user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            # that code code above mean that if you change the password while you're logging in you keep your accounts login
            return redirect('/accounts/profile/')
    context={
        'form':form
    }
    return render(request, 'register/change_password.html', context)





    

register/templates/register/change_password.html
{% extends 'base.html' %}
{% block title %}Edit Article{% endblock %}
{% load static %}
{% block main %}
<style>
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
</style>

<div class="container emp-profile">
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.old_password.label}}
    {{form.old_password}}
    <br>
    {{form.new_password1.label}}
    {{form.new_password1}}
    <br>
    {{form.new_password2.label}}
    {{form.new_password2}}
    <br>
    <button type="submit" class="btn btn-primary" >Edit Profile</button>
</form>
<br><br>
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

</div> 

{% endblock %}

register/templates/register/create_account_page.html
{% extends 'base.html' %}
{% block title %}Edit Article{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
        <h3>😝Register😝</h3>
    </div>
    <div class="card-body">
      <form action="" method="POST">
          {% csrf_token %}
          <div class="form-row">
            <div class="col">
              {{form.first_name}}
            </div>
            <div class="col">
                {{form.last_name}}
            </div>
          </div>
          <br>
          {{form.username.label}}: <br>
          {{form.username}}
          <br><br>
          {{form.email.label}}
          <br>
          {{form.email}}
          <br><br>
          {{form.password1.label}}
          <br>
          {{form.password1}}
          <br><br>
          {{form.password2.label}}
          <br>
          {{form.password2}}
          <br><br>
          <button type="submit" class="btn btn-primary" >Register</button>
          <br><br>


          {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
          {% endif %}




          {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                  {{message}}
                </div>
                {% endfor %}
            {% endif %}
          <br>
          Did you have already an accout ? What do you waiting for <a href="{% url 'register:login_page' %}">Login</a>
      </form>

    </div>
  </div>
{% endblock %}

register/templates/register/edit_profile.html
{% extends 'base.html' %}
{% block title %}Edit Profile{% endblock %}
{% load static %}
{% block main %}
<style>
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
</style>

<div class="container emp-profile">
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.first_name.label}}
    {{form.first_name}}
    <br>
    {{form.last_name.label}}
    {{form.last_name}}
    <br>
    {{form.email.label}}
    {{form.email}}
    <br>
    {{form.phone.label}}
    {{form.phone}}
    <br>
    {{form.city.label}}
    {{form.city}}
    <br>
    {{form.bio.label}}
    {{form.bio}}
    <br>
    <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupFileAddon01">Upload</span>
        </div>
        <div class="custom-file">
          {{form.image}}
          <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
        </div>
      </div>
    <br>
    {{form.profession.label}}
    {{form.profession}}
    <br>
    {{form.skills.label}}
    {{form.skills}}
    <br>
    <a href="#" class="btn btn-outline-dark">Add Some Skills</a><br><br>
    <button type="submit" class="btn btn-primary" >Edit Profile</button>
</form>

</div> 

{% endblock %}

register/templates/register/login_page.html
{% extends 'base.html' %}
{% block title %}Edit Article{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
        <h3>😝Login Now😝</h3>
    </div>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleInputEmail1">Username</label>
              <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username" placeholder='enter your username here ..'>
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
              <label for="exampleInputPassword1">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder='enter your password here ..'>
            </div>
            <br>
            <button type="submit" class="btn btn-outline-dark">Login</button>
            <br>
            <br>

            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                  {{message}}
                </div>
                {% endfor %}
            {% endif %}


            <br>
            Did you forget your password ? You could reset it <a href="">Here</a><br>
            Don't you Have an account ? Register <a href="{% url 'register:create_account_page' %}">Here</a>  
          </form>

    </div>
  </div>
{% endblock %}

register/templates/register/membership.html
{% extends 'base.html' %}
{% block title %}Membership{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
        <h3>😝Do want to be a member of this Website😝</h3>
    </div>
    <div class="card-body">
      <h4>Do you have an account ? if you do : </h4>
      <a href="{% url 'register:login_page' %}" class="btn btn-outline-secondary">Login 😋</a>
      <h4>If you don't : </h4>
      <a href="{% url 'register:create_account_page' %}" class="btn btn-outline-primary">Create an account 😋</a>

    </div>
  </div>
{% endblock %}

register/templates/register/profile.html
{% extends 'base.html' %}
{% block title %}Edit Article{% endblock %}
{% load static %}
{% block main %}


<style>
    body{
    background: -webkit-linear-gradient(left, #a3a3a3, #ececec);
}
.emp-profile{
    padding: 3%;
    margin-top: 3%;
    margin-bottom: 3%;
    border-radius: 0.5rem;
    background: #fff;
}
.profile-img{
    text-align: center;
}
.profile-img img{
    width: 70%;
    height: 100%;
}
.profile-img .file {
    position: relative;
    overflow: hidden;
    margin-top: -20%;
    width: 70%;
    border: none;
    border-radius: 0;
    font-size: 15px;
    background: #212529b8;
}
.profile-img .file input {
    position: absolute;
    opacity: 0;
    right: 0;
    top: 0;
}
.profile-head h5{
    color: #333;
}
.profile-head h6{
    color: #a8a8a8;
}
.profile-edit-btn{
    border: none;
    border-radius: 1.5rem;
    width: 70%;
    padding: 2%;
    font-weight: 600;
    color: #6c757d;
    cursor: pointer;
}
.proile-rating{
    font-size: 12px;
    color: #818182;
    margin-top: 5%;
}
.proile-rating span{
    color: #495057;
    font-size: 15px;
    font-weight: 600;
}
.profile-head .nav-tabs{
    margin-bottom:5%;
}
.profile-head .nav-tabs .nav-link{
    font-weight:600;
    border: none;
}
.profile-head .nav-tabs .nav-link.active{
    border: none;
    border-bottom:2px solid #a8a8a8;
}
.profile-work{
    padding: 14%;
    margin-top: -15%;
}
.profile-work p{
    font-size: 12px;
    color: #818182;
    font-weight: 600;
    margin-top: 10%;
}
.profile-work a{
    text-decoration: none;
    color: #495057;
    font-weight: 600;
    font-size: 14px;
}
.profile-work ul{
    list-style: none;
}
.profile-tab label{
    font-weight: 600;
}
.profile-tab p{
    font-weight: 600;
    color: #a8a8a8;
}
</style>





<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
            <form method="post">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            {% if request.user.profile.image %}
                            <img src="{{request.user.profile.image.url}}" alt=""/>
                            {% endif %}
                        </div>
                        <br>
                    </div>
                    <div class="col-md-6">
                        <div class="profile-head">
                                    <h5>
                                        {{user.first_name}} {{user.last_name}}
                                    </h5>
                                    <h6>
                                        {{user.profession}}
                                    </h6>
                                    <br>
                                    <br><br>
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'register:edit_profile' %}" class="btn btn-outline-dark">Edit your Profile</a><br><br>
                        <a href="{% url 'register:change_password' %}" class="btn btn-outline-dark">Change Password</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <p>SKILLS</p>
                            {% for skill in user.skills.all %}
                                <a href="">{{skill}}</a><br/>
                            {% endfor %}
                            <!-- <a href="">Web Designer</a><br/>
                            <a href="">Web Developer</a><br/>
                            <a href="">WordPress</a><br/>
                            <a href="">WooCommerce</a><br/>
                            <a href="">PHP, .Net</a><br/> -->
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Username</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{request.user|title}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Name</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{user.first_name}} {{user.last_name}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Email</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{user.email}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Phone</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{user.phone}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label>Profession</label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{user.profession}}</p>
                                            </div>
                                        </div>
                            </div>
                            <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Location</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.city}}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Your Bio</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{user.bio}}</p>
                                    </div>
                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
            </form>           
        </div>
{% endblock %}