main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.articles, name='articles'),
    path('add_article/', views.add_article, name='add_article'),
    path('edit/<str:pk>/', views.edit_article, name='edit_article'),
    path('delete/<str:pk>/', views.delete_article, name='delete_article'),
    path('<str:pk>/', views.details, name='details'),

    
]

prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views as v

urlpatterns = [
    path('', v.home, name='home'),
    path('contact_us/', v.contact_us, name='contact_us'),
    path('accounts/', include('register.urls', namespace='register')),
    path('articles/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

register/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views


from . import views
app_name = 'register'
urlpatterns = [
    path('', views.membership, name='membership'),
    path('login/', views.login_page, name='login_page'),
    path('register/', views.create_account_page, name='create_account_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),








]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Krona+One&family=Lobster&family=Monda&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    {% include 'navbar.html' %}
    <div class="container main_container">
        {% block main %}{% endblock %}
    </div>
    

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/" style="font-family: 'Krona One', sans-serif;font-size: 25px;">Med News</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">All Articles <span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:articles' %}">My Articles</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact_us' %}">Contact Us</a>
        </li>
      </ul>
    </div>
    {% if request.user.is_authenticated %}
    <a href="{% url 'register:profile' %}" class="btn btn-outline-dark" style="margin-right: 10px;">{{request.user|title}}</a>
    <a href="{% url 'register:logout_page' %}" class="btn btn-outline-dark">Logout</a>
    {% else %}
    <a href="{% url 'register:membership' %}" class="btn btn-outline-dark">Membership</a>
    {% endif %}
  </nav>