main/urls.py
from django.urls import path
from . import views
app_name = 'main'
urlpatterns = [
    path('', views.articles, name='articles'),
    path('add_article/', views.add_article, name='add_article'),
    path('edit/<str:pk>/', views.edit_article, name='edit_article'),
    path('delete/<str:pk>/', views.delete_article, name='delete_article'),
    path('<str:pk>/', views.details, name='details'),

    
]

prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views as v

urlpatterns = [
    path('', v.home, name='home'),
    path('contact_us/', v.contact_us, name='contact_us'),
    path('accounts/', include('register.urls', namespace='register')),
    path('articles/', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),


    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

register/urls.py
from django.urls import path, include

from django.contrib.auth import views as auth_views


from . import views
app_name = 'register'
urlpatterns = [
    path('', views.membership, name='membership'),
    path('login/', views.login_page, name='login_page'),
    path('register/', views.create_account_page, name='create_account_page'),
    path('logout/', views.logout_page, name='logout_page'),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),








]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
# Create your models here.

class Article(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,blank=True)
    title = models.CharField(max_length=250, null=True)
    content = RichTextField(null=True)
    source = models.CharField(max_length=250, null=True)
    image = models.ImageField(upload_to='article_img/',null=True,blank=True)
    published_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    writer = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE,null=True,blank=True)
    published_at = models.DateTimeField(auto_now=True)
    message = models.TextField(null=True)

    def __str__(self):
        return str(self.writer)

main/forms.py
from django import forms
from .models import *
from ckeditor.widgets import CKEditorWidget
class ArticleForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model=Article
        fields='__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Write the Title here .. '}),
            # 'content': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Write the Content here .. '}),
            'source': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Write the Source here .. '}),
            'image': forms.FileInput(attrs={'class':'custom-file-input','id':'inputGroupFile01','aria-describedby':'inputGroupFileAddon01'}),

            
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields=['message']
        widgets = {
            'message': forms.Textarea(attrs={'class':'form-control', 'placeholder':'What are you thinking...', 'id':'message', 'rows':'3'}),
        }

main/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core.paginator import Paginator
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.conf import settings


def home(request):
    articles = Article.objects.all().order_by('-published_at')
    paginator = Paginator(articles, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles':articles,
        'page_obj':page_obj,
        'paginator':paginator,
    }
    return render(request, 'main/home.html', context)


@login_required(login_url='/accounts')
def articles(request):
    articles = request.user.article_set.all().order_by('-published_at')
    paginator = Paginator(articles, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'articles':articles,
        'page_obj':page_obj,
        'paginator':paginator,
    }
    return render(request, 'main/articles.html', context)


def details(request, pk):
    article = Article.objects.get(id=pk)
    comments = Comment.objects.filter(article=article).order_by('-published_at')
    comments_form = CommentForm()
    if request.method=='POST':
        comments_form = CommentForm(request.POST)
        if comments_form.is_valid():
            new_form = comments_form.save(commit=False)
            new_form.writer = request.user
            new_form.article = article
            new_form.save()
    context = {
        'article':article,
        'comments':comments,
        'comments_form':comments_form,
    }
    return render(request, 'main/details.html', context)

@login_required(login_url='/accounts')
def add_article(request):
    form = ArticleForm()
    if request.method=='POST':
        form = ArticleForm(request.POST,request.FILES)
        if form.is_valid():
            new_form=form.save()
            new_form.user = request.user
            new_form.save()
            article_name = new_form.title
            messages.success(request, 'Your article "'+article_name+'" has created ' )
            return redirect('/articles')
    context = {
        'form':form
    }
    return render(request, 'main/add_article.html', context)


@login_required(login_url='/accounts')
def edit_article(request, pk):
    data = Article.objects.get(id=pk)
    form = ArticleForm(instance=data)
    if request.method=='POST':
        form = ArticleForm(request.POST,request.FILES,instance=data)
        if form.is_valid():
            new_form=form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/articles')
    context = {
        'form':form
    }
    return render(request, 'main/edit_article.html', context)

@login_required(login_url='/accounts')
def delete_article(request, pk):
    article = Article.objects.get(id=pk)
    if request.method=='POST':
        article.delete()
        return redirect('/articles')
    context = {
        'article':article
    }
    return render(request, 'main/delete_article.html', context)


def contact_us(request):
    if request.method=='POST':
        name = request.POST['txtName']
        email = request.POST['txtEmail']
        subject = request.POST['txtSubject']
        msg = request.POST['txtMsg']
        send_mail(
            subject,
            msg,
            settings.EMAIL_HOST_USER,
            [email],
        )
    return render(request, 'main/contact_us.html')

main/templates/main/add_article.html
{% extends 'base.html' %}
{% block title %}Add Article{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
      Add Article
    </div>
    <div class="card-body">
      <h5 class="card-title">New Post</h5>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form.title.label}} : 
        <br>
        {{form.title}}
        <br>
        <br>
        <br>
        {{form.content.label}} : 
        <br>
        {{form.content}}
        <br><br><br>
        {{form.source.label}} : 
        <br>
        {{form.source}}
        <br><br><br>
        {{form.image.label}} :
            <br>
        <div class="input-group mb-3">
            <div class="custom-file">
              {{form.image}}
              <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Add New Article</button>
    </form>

    </div>
  </div>
{% endblock %}

main/templates/main/articles.html
{% extends 'base.html' %}
{% block title %}Articles{% endblock %}
{% load static %}
{% block main %}

<style>
  .emp-profile{
      padding: 3%;
      margin-top: 3%;
      margin-bottom: 3%;
      border-radius: 0.5rem;
      background: #fff;
  }
</style>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
</ul>
{% endif %}
<div class="card text-center emp-profile">
  <div class="card-body">
    <a href="{% url 'main:add_article' %}" class="btn btn-outline-success">Add Article</a>
    <div class="row">
        {% for article in page_obj %}
        <div class="card ar_div" style="width: 18rem;">
            <img src="{{article.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title" style="font-family: 'Monda', sans-serif;">{{article.title}}</h5>
              <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
              <a href="{% url 'main:details' article.id %}" class="btn btn-outline-primary">Read More</a>
            </div>
            <div class="container">
              <a href="{% url 'main:edit_article' article.id %}" class="btn btn-outline-info">Edit</a>
              <a href="{% url 'main:delete_article' article.id %}" class="btn btn-outline-danger">Delete</a>
            </div>
            <br>
            
          </div>
        {% endfor %}

    </div>
  </div>
</div>

<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
      </li>
    {% endif %}
    {% for x in paginator.page_range %}
      <li class="page-item"><a class="page-link" href="?page={{x}}">{{x}}</a></li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="#">Next</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#">Next</a>
      </li>
    {% endif %}
    </ul>
  </nav>

    

      


{% endblock %}

main/templates/main/contact_us.html
{% extends 'base.html' %}
{% block title %}Contant Us{% endblock %}
{% block main %}
<style>
    body{
    background: -webkit-linear-gradient(left, #a3a3a3, #ececec);
}
.contact-form{
    background: #fff;
    margin-top: 10%;
    margin-bottom: 5%;
    width: 70%;
}
.contact-form .form-control{
    border-radius:1rem;
}
.contact-image{
    text-align: center;
}
.contact-image img{
    border-radius: 6rem;
    width: 11%;
    margin-top: -3%;
    transform: rotate(29deg);
}
.contact-form form{
    padding: 14%;
}
.contact-form form .row{
    margin-bottom: -7%;
}
.contact-form h3{
    margin-bottom: 8%;
    margin-top: -10%;
    text-align: center;
    color: #0062cc;
}
.contact-form .btnContact {
    width: 50%;
    border: none;
    border-radius: 1rem;
    padding: 1.5%;
    background: #a1a1a1;
    font-weight: 600;
    color: #fff;
    cursor: pointer;
}
.btnContactSubmit
{
    width: 50%;
    border-radius: 1rem;
    padding: 1.5%;
    color: #fff;
    background-color: #0062cc;
    border: none;
    cursor: pointer;
}
</style>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<div class="container contact-form">
            <div class="contact-image">
                <img src="https://image.ibb.co/kUagtU/rocket_contact.png" alt="rocket_contact"/>
            </div>
            <form method="POST">
                {% csrf_token %}
                <h3 style="color: #000000;">Drop Us a Message</h3>
               <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <input type="text" name="txtName" class="form-control" placeholder="Your Name *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtEmail" class="form-control" placeholder="Your Email *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="text" name="txtSubject" class="form-control" placeholder="Your Subject Number *" value="" />
                        </div>
                        <div class="form-group">
                            <input type="submit" name="btnSubmit" class="btnContact" value="Send Message" />
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <textarea name="txtMsg" class="form-control" placeholder="Your Message *" style="width: 100%; height: 150px;"></textarea>
                        </div>
                    </div>
                </div>
            </form>
</div>
{% endblock %}

main/templates/main/delete_article.html
{% extends 'base.html' %}
{% block title %}Delete Article{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
      Delete Article
    </div>
    <div class="card-body">
      <h5 class="card-title">Are you sure 😢</h5>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h4>Are you sure that you want to delete "{{article.title}}" 😭 .</h4>
        <a href="{% url 'main:articles' %}" class="btn btn-warning">Cancel</a>
        <button type="submit" class="btn btn-danger">Yes, I'm sure</button>
    </form>

    </div>
  </div>
{% endblock %}

main/templates/main/details.html
{% extends 'base.html' %}
{% block title %}{{article.title}}{% endblock %}
{% load static %}
{% block main %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
<!------ Include the above in your HEAD tag ---------->
<!------ Include the above in your HEAD tag ---------->

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<style>
  .h7
		{
			font-size: 0.9rem;
		}
  .emp-profile{
      padding: 3%;
      margin-top: 3%;
      margin-bottom: 3%;
      border-radius: 0.5rem;
      background: #fff;

  }
  /* CSS Test begin */
.comment-box {
    margin-top: 30px !important;
}
/* CSS Test end */

.comment-box img {
    width: 50px;
    height: 50px;
}
.comment-box .media-left {
    padding-right: 10px;
    width: 65px;
}
.comment-box .media-body p {
    border: 1px solid #ddd;
    padding: 10px;
}
.comment-box .media-body .media p {
    margin-bottom: 0;
}
.comment-box .media-heading {
    background-color: #f5f5f5;
    border: 1px solid #ddd;
    padding: 7px 10px;
    position: relative;
    margin-bottom: -1px;
}
.comment-box .media-heading:before {
    content: "";
    width: 12px;
    height: 12px;
    background-color: #f5f5f5;
    border: 1px solid #ddd;
    border-width: 1px 0 0 1px;
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
    position: absolute;
    top: 10px;
    left: -6px;
}
</style>
<div class="card">
    <div class="card-body">
      <h3 class="card-title">{{article.title}}</h3>
      <p class="card-text"><small class="text-muted">Reviewed by "{{article.user}}"</small></p>
      <p class="card-text">{{article.content|safe}}</p>
      <p class="card-text"><small class="text-muted">Last updated in {{article.published_at}}</small></p>
      
    </div>
    <img src="{{article.image.url}}" class="card-img-top" alt="...">
  </div>
  


<div class="card text-center emp-profile">
    <div class="card-body">
        <h3 class="card-title">🥳Comment : there is {{comments.count}} comments🥳</h3>
        {% if request.user.is_authenticated %}
        <form action="" method="POST">
          {% csrf_token %}
        				<!--- Post Form Begins -->
                <section class="card">
                  <div class="card-header">
                      <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                          <li class="nav-item">
                              <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                                  a Post</a>
                          </li>
                      </ul>
                  </div>
                  <div class="card-body">
                      <div class="tab-content" id="myTabContent">
                          <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                              <div class="form-group">
                                  <label class="sr-only" for="message">post</label>
                                  {{comments_form.message}}
                              </div>

                          </div>
                      </div>
                      <div class="text-right">
                        <button type="submit" class="btn btn-success">share</button>
                      </div>
                  </div>
              </section>
              <!--- Post Form Ends -->
        </form>
        {% else %}
        <br><br><br>
        <h2>To add a comment Just login</h2>
        <a href="{% url 'register:membership' %}" class="btn btn-warning">Go To Membership</a>
        <br><br>
        {% endif %}
        {% for comment in comments %}
        <div class="media comment-box">
          <div class="media-left">
              <a href="#">
                  <img class="img-responsive user-photo" src="{{comment.writer.profile.image.url}}">
              </a>
          </div>
          <div class="media-body">
              <h4 class="media-heading">{{comment.writer}}</h4>
              <p>{{comment.message}}</p>
            
          </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

<!-- <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" alt=""> -->

main/templates/main/edit_article.html
{% extends 'base.html' %}
{% block title %}Edit Article{% endblock %}
{% load static %}
{% block main %}


<div class="card text-center">
    <div class="card-header">
      Edit Article
    </div>
    <div class="card-body">
      <h5 class="card-title">Change something in this Post !!</h5>
      <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {{form.title.label}} : 
        <br>
        {{form.title}}
        <br>
        <br>
        <br>
        {{form.content.label}} : 
        <br>
        {{form.content}}
        <br><br><br>
        {{form.source.label}} : 
        <br>
        {{form.source}}
        <br><br><br>
        {{form.image.label}} :
            <br>
        <div class="input-group mb-3">
            <div class="custom-file">
              {{form.image}}
              <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Edit this Article</button>
    </form>

    </div>
  </div>
{% endblock %}

main/templates/main/home.html
{% extends 'base.html' %}
{% block title %}Med News{% endblock %}
{% block main %}
{% if messages %}
  {% for message in messages %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endfor %}
{% endif %}
<style>
    .emp-profile{
        padding: 3%;
        margin-top: 3%;
        margin-bottom: 3%;
        border-radius: 0.5rem;
        background: #fff;
    }
    </style>
    {% if not request.user.is_authenticated %}
    <div class="card text-center emp-profile">
        <div class="card-body">
            <h5 class="card-title">🥳Welcome Guys to the best Website which give the beset Medical News ever.🥳</h5>
            <p class="card-text">👉 You can find here every thing about medcine you can even create an account and start posting some great article 👈 <br> 🤩 enjoy 🤩 </p>
            <a href="{% url 'register:membership' %}" class="btn btn-outline-warning">Let's get started 👉</a>
        </div>
    </div>
    {% endif %}
    

    <div class="card text-center emp-profile">
            <div class="row" >
                {% for article in page_obj %}
                <div class="card ar_div" style="width: 18rem;">
                    <img src="{{article.image.url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                    <h5 class="card-title" style="font-family: 'Monda', sans-serif;">{{article.title}}</h5>
                    <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> -->
                    </div>
                    <div class="container">
                      <a href="{% url 'main:details' article.id %}" class="btn btn-outline-primary">Read More ...</a>
                    </div>
                    <br>
                </div>
                {% endfor %}
            </div>
            
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
          </li>
        {% endif %}
        {% for x in paginator.page_range %}
          <li class="page-item"><a class="page-link" href="?page={{x}}">{{x}}</a></li>
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="#">Next</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#">Next</a>
          </li>
        {% endif %}
        </ul>
      </nav>



{% endblock %}